-- 合同管理表
CREATE TABLE IF NOT EXISTS `contracts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `contract_no` VARCHAR(50) NOT NULL COMMENT '合同编号',
  `title` VARCHAR(200) NOT NULL COMMENT '合同标题',
  `customer_id` BIGINT COMMENT '客户ID',
  `customer_name` VARCHAR(100) COMMENT '客户名称',
  `lead_id` BIGINT COMMENT '线索ID',
  `amount` DECIMAL(15,2) DEFAULT 0 COMMENT '合同金额',
  `status` VARCHAR(20) DEFAULT 'draft' COMMENT '状态: draft/active/completed/terminated',
  `sign_date` DATE COMMENT '签订日期',
  `start_date` DATE COMMENT '开始日期',
  `end_date` DATE COMMENT '结束日期',
  `attachment_url` VARCHAR(500) COMMENT '附件URL',
  `terms` TEXT COMMENT '合同条款',
  `payment_terms` VARCHAR(500) COMMENT '付款条款',
  `notes` TEXT COMMENT '备注',
  `created_by`创建人',
 BIGINT COMMENT '  `assigned_to` BIGINT COMMENT '负责人',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_contract_no` (`contract_no`),
  INDEX `idx_customer_id` (`customer_id`),
  INDEX `idx_lead_id` (`lead_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同表';
