-- 发票管理表
CREATE TABLE IF NOT EXISTS `invoices` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `invoice_no` VARCHAR(50) NOT NULL COMMENT '发票编号',
  `order_id` BIGINT COMMENT '订单ID',
  `order_no` VARCHAR(50) COMMENT '订单编号',
  `customer_id` BIGINT COMMENT '客户ID',
  `customer_name` VARCHAR(100) COMMENT '客户名称',
  `type` VARCHAR(20) DEFAULT 'vat' COMMENT '发票类型: vat(增值税发票)/普通发票/电子发票',
  `status` VARCHAR(20) DEFAULT 'draft' COMMENT '状态: draft/issued/cancelled/paid',
  `amount` DECIMAL(15,2) DEFAULT 0 COMMENT '金额',
  `tax_amount` DECIMAL(15,2) DEFAULT 0 COMMENT '税额',
  `total_amount` DECIMAL(15,2) DEFAULT 0 COMMENT '价税合计',
  `tax_rate` VARCHAR(10) DEFAULT '13%' COMMENT '税率',
  `issue_date` DATE COMMENT '开票日期',
  `due_date` DATE COMMENT '到期日期',
  `actual_payment_date` DATE COMMENT '实际付款日期',
  `title` VARCHAR(200) COMMENT '发票抬头',
  `tax_number` VARCHAR(50) COMMENT '税号',
  `bank_name` VARCHAR(100) COMMENT '开户行',
  `bank_account` VARCHAR(50) COMMENT '银行账号',
  `address` VARCHAR(200) COMMENT '地址',
  `phone` VARCHAR(20) COMMENT '电话',
  `email` VARCHAR(100) COMMENT '邮箱',
  `billing_type` VARCHAR(20) COMMENT '开票方式',
  `content` TEXT COMMENT '发票内容',
  `remark` VARCHAR(500) COMMENT '备注',
  `attachment_url` VARCHAR(500) COMMENT '附件URL',
  `payment_status` VARCHAR(20) DEFAULT 'unpaid' COMMENT '付款状态: unpaid/paid/partial',
  `invoice_url` VARCHAR(500) COMMENT '发票URL',
  `created_by` BIGINT COMMENT '创建人',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_invoice_no` (`invoice_no`),
  INDEX `idx_order_id` (`order_id`),
  INDEX `idx_customer_id` (`customer_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_type` (`type`),
  INDEX `idx_issue_date` (`issue_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='发票表';
